# Generated by Django 4.1 on 2022-08-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LP_CustomerPrincipalPayments', models.IntegerField()),
                ('LoanMonthsSinceOrigination', models.IntegerField()),
                ('LP_CustomerPayments', models.IntegerField()),
                ('ClosedDate_day', models.IntegerField()),
                ('ClosedDate_month', models.IntegerField()),
                ('EmploymentStatus_Full_time', models.IntegerField(choices=[(0, 'Not Full Time'), (1, 'Full Time')])),
                ('Investors', models.IntegerField()),
                ('MonthlyLoanPayment', models.IntegerField()),
                ('LoanOriginationQuarter_Q1_2014', models.IntegerField()),
                ('LoanOriginalAmount', models.IntegerField()),
                ('LoanOriginationQuarter_Q4_2013', models.IntegerField()),
                ('ClosedDate_year', models.IntegerField()),
                ('DateCreditPulled_year', models.IntegerField()),
                ('LoanOriginationDate_year', models.IntegerField()),
                ('ListingCreationDate_year', models.IntegerField()),
            ],
        ),
    ]
